### ISSUE TITLE
winograd bprop step

### ISSUE THREAD

**Issue by ghost** [ColfaxResearch/FALCON#1]
Hi,

Thanks a lot for your welcome contribution of a winograd fprop step for the Xeon Phi.
I successfully incorporated your code width some minor tweaks to avoid the mkl dependency.
Now I'm trying to get the bprop step working but I don't get a good result in the firts step of using the
 same winograd fprop function but with flipped filters. I'm out of ideas of what I'm doing wrong. Is it somehow possible to provide an example of the bprop step?

thanks,
filip

**Comment by sangameshnr** [comment]
I am glad that you incorporated FALCON code in your convnet. 
Yes, you have to flip the filters before you use them in the backward pass. By good result, do you mean the accuracy or the performance ?? Could you please describe your problem more so that I can understand what is happening ??

**Comment by ghost** [comment]
There is a relative big accuracy difference between the results of direct convolution and the winograd transform in the first bprop step, much bigger than in the fprop step. Big enough so I had to lower the learning rate to get the same results as with direct convolution. In the paper by A.Lavin and S.Gray the accuracy of the winograd F(2x2,3x3) transform was described as even a bit higher over direct convolution so I was under the false impression I did something wrong :) Now I'm going to try to implement bprop step #2 with the F(3x3,2x2) transform. 
Thanks again for the excellent FALCON code sample,
filip
